name: deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SLEDGEMP_PRIVATE_KEY_DEV }}
          port: ${{ secrets.PORT }}
          script: ./TeardownNakamaServer/scripts/build_latest.sh --yes
